# Это имя отобразится во вкладке Actions на GitHub
name: "Twitch Proxy Farm Bot"

on:
  workflow_dispatch: # Кнопка ручного запуска

jobs:
  twitch_job:
    # Имя конкретной задачи в логах
    name: "Running 5 Twitch Bots"
    runs-on: ubuntu-latest

    steps:
    - name: "Checking out code from repository"
      uses: actions/checkout@v4

    - name: "Setting up Python environment"
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: "Installing FFMPEG system dependency"
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: "Installing Python dependencies (Requests & Streamlink)"
      run: |
        pip install requests streamlink

    - name: "Executing twitch_github.py script"
      run: python twitch_github.py
